// Transcribed receipt samples: dates, tables, payment methods, quantities and sizes.
// Prices and service timestamps were not supplied; the demo supplies those separately.
export const receipts = [
  ["2026-09-20", "Gazebo", null, "cash", [[1, "Creamy Carbonara", "Regular"], [1, "Matcha Blueberry Latte", "22oz"], [2, "Spanish Latte", "Cold 22oz"], [1, "Grilled Liempo", "Regular"], [1, "Burger Steak", "Regular"], [1, "Caramel Macchiato", "Cold 22oz"], [1, "American Breakfast", "Regular"]]],
  ["2026-09-20", "Lanai", null, "maya", [[1, "Caesar Salad", "Regular"], [1, "Clubhouse", "Regular"], [2, "Spanish Latte", "Cold 22oz"]]],
  ["2026-09-20", "Dome", null, "cash", [[1, "Biscoff Latte", "22oz"], [1, "Cookies & Cream Frappe", "22oz"], [1, "Matcha Strawberry Latte", "22oz"], [1, "Toyomansi Porkchop", "Regular"], [1, "Creamy Carbonara", "Regular"], [1, "Homemade Tocilog", "Regular"], [1, "Abbey's Signature Tapsilog", "Regular"]]],
  ["2026-09-20", "Lanai", null, "cash", [[1, "Caramel Macchiato", "Cold 22oz"], [2, "Salted Caramel Frappe", "22oz"], [1, "Nachos", "Regular"], [1, "Baked Penne", "Regular"], [1, "Meatball Spaghetti", "Regular"]]],
  ["2026-09-20", "Tent 2", null, "cash", [[1, "White Chocolate", "Cold 22oz"], [1, "Caramel Macchiato", "Cold 22oz"]]],
  ["2026-09-20", "Tent 2", null, "cash", [[1, "Biscoff Latte", "22oz"], [1, "Matcha Strawberry Latte", "22oz"], [1, "Cheesy Tuna Pesto", "Regular"]]],
  ["2026-09-20", "Lanai", null, "cash", [[1, "Choco Hazelnut", "Cold 22oz"]]],
  ["2026-09-20", "Takeout", null, "cash", [[1, "Biscoff Latte", "22oz"], [1, "White Chocolate Frappe", "22oz"], [1, "Salted Caramel Frappe", "22oz"], [1, "Creamy Carbonara", "Regular"], [1, "Baked Penne", "Regular"]]],
  ["2026-09-20", "Lanai", null, "cash", [[1, "Mini Donuts", "Choco"], [1, "Spanish Latte", "Cold 22oz"], [1, "Strawberry Fruit Tea", "22oz"], [1, "Salted Caramel Frappe", "22oz"]]],
  ["2026-09-20", "Indoor", null, "maya", [[2, "Chicken Ala King", "Regular"], [1, "Abbey's Signature Tapsilog", "Regular"], [1, "Abbey's Bibimbowl", "Regular"], [2, "Abbey's Signature Fried Chicken", "Regular"]]],
  ["2026-09-20", "Tent 1", null, "maya", [[1, "Spanish Latte", "Cold 22oz"], [1, "White Chocolate", "Cold 22oz"], [1, "Biscoff Latte", "22oz"], [1, "Red Velvet Frappe", "22oz"], [1, "Street Food Platter", "Regular"], [2, "Cheesy Tuna Pesto", "Regular"]]],
  ["2026-09-20", "Tent 2", null, "cash", [[1, "Grilled Liempo", "Regular"], [1, "Abbey's Signature Tapsilog", "Regular"], [1, "Caesar Salad", "Regular"], [1, "Spanish Latte", "Cold 22oz"]]],
  ["2026-09-20", "Indoor", null, "cash", [[1, "Crispy Kare Kare", "Solo"], [1, "Grilled Liempo", "Regular"], [2, "Abbey's Signature Tapsilog", "Regular"], [1, "Fried Rice", "Regular"]]],
  ["2026-09-20", "Takeout", "Ate Maye", "cash", [[1, "Pork Butterfly Steak", "Solo"], [1, "Toyomansi Porkchop", "Regular"], [1, "Abbey's Bibimbowl", "Regular"], [1, "Blueberry Fruit Tea", "22oz"], [1, "Strawberry Fruit Tea", "22oz"], [1, "Strawberry Probiotic", "22oz"]]],
  ["2026-09-20", "Gazebo", null, "cash", [[1, "Strawberry Fruit Tea", "16oz"], [1, "White Chocolate", "Hot 16oz"]]],
  ["2026-09-20", "Takeout", "Sir Ken", "maya", [[1, "Chicken Neck", "Regular"], [1, "Extra Rice", "Regular"], [1, "Crispy Pork Sinigang", "Solo"]]],
  ["2026-09-20", "Indoor", null, "maya", [[1, "Katsu Bowl", "Regular"], [1, "Chicken Ala King", "Regular"], [1, "Spanish Latte", "Hot 16oz"], [1, "Caramel Macchiato", "Hot 16oz"]]],
  ["2026-09-20", "Tent 2", null, "cash", [[1, "Biscoff Latte", "22oz"], [1, "Matcha Latte", "22oz"], [1, "Crispy Kare Kare", "Solo"], [1, "Cheesy Tuna Pesto", "Regular"]]],
  ["2026-09-13", "Tent 2", null, "cash", [[1, "Matcha Frappe", "16oz"], [1, "Mocha Frappe", "16oz"]]],
  ["2026-09-13", "Indoor", null, "cash", [[1, "Matcha Frappe", "22oz"], [1, "Matcha Latte", "22oz"], [1, "Clubhouse", "Regular"], [1, "Chicken Ala King", "Regular"]]],
  ["2026-09-13", "Indoor", null, "maya", [[1, "Abbey's Bibimbowl", "Regular"], [1, "Chicken Ala King", "Regular"], [1, "Caramel Macchiato", "Hot 16oz"], [1, "Caramel Latte & Vanilla Cream", "Hot 16oz"], [1, "French Fries", "Sour Cream"]]],
  ["2026-09-13", "Lanai", null, "cash", [[2, "Spanish Latte", "Cold 16oz"], [1, "Grilled Liempo", "Regular"], [1, "Abbey's Signature Fried Chicken", "Regular"], [1, "French Fries", "Cheese"]]],
  ["2026-09-13", "Indoor", null, "cash", [[1, "Vanilla Latte", "Hot 16oz"], [1, "Caramel Latte & Vanilla Cream", "Hot 16oz"], [1, "French Fries", "BBQ"]]],
  ["2026-09-13", "Indoor", null, "cash", [[1, "Chicken Ala King", "Regular"], [1, "Katsu Bowl", "Regular"], [1, "Spanish Latte", "Hot 16oz"], [1, "Caramel Macchiato", "Hot 16oz"]]],
  ["2026-09-13", "Takeout", null, "cash", [[1, "White Chocolate", "Hot 16oz"], [1, "Choco Frappe", "16oz"], [1, "Matcha Salted Caramel", "16oz"]]],
  ["2026-09-13", "Lanai 1", null, "cash", [[1, "Matcha Strawberry Latte", "16oz"], [1, "Choco Frappe", "16oz"], [3, "Matcha Latte", "16oz"], [1, "Spanish Latte", "Hot 16oz"], [1, "Sausilog", "Regular"], [1, "French Fries", "BBQ"]]],
  ["2026-09-13", "Takeout", null, "maya", [[1, "Choco Salted Cream Cheese Frappe", "22oz"], [1, "Matcha Frappe", "22oz"], [1, "Caramel Latte & Vanilla Cream", "Cold 22oz"], [1, "Caramel Macchiato", "Cold 22oz"], [1, "Red Velvet Frappe", "22oz"], [1, "Mango Frappe", "22oz"], [1, "French Fries", "BBQ"], [1, "French Fries", "Sour Cream"], [1, "Choco Salted Cream Cheese Frappe", "22oz"], [1, "Katsu Bowl", "Regular"]]],
  ["2026-09-06", "Gazebo", null, "maya", [[1, "Caramel Macchiato", "Hot 16oz"], [1, "Salted Caramel Frappe", "22oz"], [1, "Creamy Carbonara", "Regular"], [1, "Biscoff Latte", "22oz"]]],
  ["2026-09-19", "Lanai", null, "cash", [[1, "Chicken BBQ", "Regular"], [1, "Caesar Salad", "Regular"], [1, "Biscoff Latte", "22oz"], [1, "Cookies & Cream Frappe", "22oz"], [1, "Matcha Strawberry Latte", "22oz"]]],
  ["2026-09-19", "Lanai", null, "cash", [[1, "French Fries", "Cheese"]]],
  ["2026-09-19", "Tent 1", null, "cash", [[1, "Spanish Latte", "Cold 22oz"], [1, "White Chocolate", "Cold 22oz"]]],
  ["2026-09-19", "Takeout", null, "cash", [[1, "White Chocolate", "Cold 22oz"], [1, "Spanish Latte", "Hot 16oz"]]],
  ["2026-09-19", "Lanai", null, "cash", [[1, "Choco Frappe", "16oz"], [1, "Matcha Frappe", "22oz"], [1, "Mini Donuts", "Choco"]]],
  ["2026-09-19", "Gazebo", null, "cash", [[1, "Spanish Latte", "Cold 22oz"], [1, "White Chocolate Frappe", "22oz"], [1, "Caramel Macchiato", "Cold 22oz"], [1, "Mango Probiotic", "22oz"], [1, "French Fries", "Cheese"]]],
  ["2026-09-19", "Tent 5", null, "cash", [[2, "Choco Frappe", "22oz"], [1, "Caramel Macchiato", "Cold 22oz"], [1, "Creamy Carbonara", "Regular"]]],
  ["2026-09-19", "Gazebo", null, "cash", [[1, "Mango Frappe", "22oz"], [1, "Choco Frappe", "22oz"], [3, "Matcha Frappe", "22oz"]]],
  ["2026-09-18", "Tent 5", null, "cash", [[1, "Grilled Liempo", "Regular"], [1, "Crispy Kare Kare", "Solo"], [1, "Clubhouse", "Regular"], [1, "Matcha Latte", "22oz"], [1, "Creamy Carbonara", "Regular"]]],
];

