import { dashboardRepository } from "./dashboard.repository.js";

export const dashboardService = {
  async getData(dateFrom, dateTo) {
    const [
      todayKpis,
      periodKpis,
      previousPeriodKpis,
      revenueTrend,
      ordersByStatus,
      ordersBySource,
      topProducts,
      leastProducts,
      topVariants,
      salesByCategory,
      variantPerformance,
      ingredientStatus,
      lowStockIngredients,
      ingredientCosts,
      mostRestocked,
      ordersByHour,
      ordersByDayOfWeek,
      cancellationReasons,
      fulfillmentTime,
      tableUtilization,
      staffPerformance,
      cogs,
      cancellationRate,
      profit,
    ] = await Promise.all([
      dashboardRepository.getTodayKpis(),
      dashboardRepository.getOrderKpis(dateFrom, dateTo),
      dashboardRepository.getPreviousPeriodKpis(dateFrom, dateTo),
      dashboardRepository.getDailyRevenueTrend(dateFrom, dateTo),
      dashboardRepository.getOrdersByStatus(),
      dashboardRepository.getOrdersBySource(dateFrom, dateTo),
      dashboardRepository.getTopProducts(10, dateFrom, dateTo),
      dashboardRepository.getLeastProducts(10, dateFrom, dateTo),
      dashboardRepository.getTopVariants(10, dateFrom, dateTo),
      dashboardRepository.getSalesByCategory(dateFrom, dateTo),
      dashboardRepository.getVariantPerformance(null, dateFrom, dateTo),
      dashboardRepository.getIngredientStockStatus(),
      dashboardRepository.getLowStockIngredients(),
      dashboardRepository.getIngredientCosts(10),
      dashboardRepository.getMostRestocked(10),
      dashboardRepository.getOrdersByHour(dateFrom, dateTo),
      dashboardRepository.getOrdersByDayOfWeek(dateFrom, dateTo),
      dashboardRepository.getCancellationReasons(dateFrom, dateTo),
      dashboardRepository.getFulfillmentTime(dateFrom, dateTo),
      dashboardRepository.getTableUtilization(dateFrom, dateTo),
      dashboardRepository.getStaffPerformance(dateFrom, dateTo),
      dashboardRepository.getCOGS(dateFrom, dateTo),
      dashboardRepository.getCancellationRate(dateFrom, dateTo),
      dashboardRepository.getProfit(dateFrom, dateTo),
    ]);

    const calcDelta = (current, previous) => {
      if (!previous || previous === 0) return null;
      return Math.round(((current - previous) / previous) * 1000) / 10;
    };

    return {
      kpis: {
        revenueToday: todayKpis.revenue,
        ordersToday: todayKpis.orders,
        aovToday: todayKpis.aov,
        revenuePeriod: periodKpis.revenue,
        ordersPeriod: periodKpis.orders,
        aovPeriod: periodKpis.aov,
        totalProducts: variantPerformance.length,
        lowStockCount: (ingredientStatus.low || 0) + (ingredientStatus.out || 0),
        cogs,
        profit: profit.profit,
        margin: profit.margin,
        cancellationRate: cancellationRate.rate,
        cancellationsCancelled: cancellationRate.cancelled,
        cancellationsTotal: cancellationRate.total,
        deltas: {
          revenue: calcDelta(periodKpis.revenue, previousPeriodKpis.revenue),
          orders: calcDelta(periodKpis.orders, previousPeriodKpis.orders),
          aov: calcDelta(Number(periodKpis.aov), Number(previousPeriodKpis.aov)),
        },
      },
      revenueTrend,
      ordersByStatus,
      ordersBySource,
      topProducts,
      leastProducts,
      topVariants,
      salesByCategory,
      variantPerformance,
      ingredientStatus,
      lowStockIngredients,
      ingredientCosts,
      mostRestocked,
      ordersByHour,
      ordersByDayOfWeek,
      cancellationReasons,
      fulfillmentTime,
      tableUtilization,
      staffPerformance,
    };
  },
};
