import {
    Sun,
    Moon,
    User,
    ArrowLeft,
    ArrowDown,
    Mail,
    Lock,
    ChefHat,
    UtensilsCrossed,
    Menu,
    X,
    ChevronLeft,
    ChevronDown,
    ChevronRight,
    Heart,
    Coffee,
    Users,
    MapPin,
    Clock,
    Phone,
    Send,
    LayoutDashboard,
    Package,
    Warehouse,
    ShoppingCart,
    TrendingUp,
    ShoppingBag,
    FileText,
    Settings,
    LogOut,
    Bell,
    Search,
    AlertTriangle,
    TrendingDown,
    Lightbulb,
    Minus,
    Edit,
    SlidersHorizontal,
    Image,
    Eye,
    EyeOff,
    Pencil,
    Trash2,
    Plus,
    Check,
    CheckCircle,
    Receipt,
    Calendar,
    Archive,
    CircleArrowRight,
    Key,
    DollarSign,
    CloudOff,
    BarChart2,
    Info,
    AlertCircle,
    Table,
    Sparkles,
    Loader,
    Camera,
    Percent,
    LayoutGrid,
    FolderPlus,
} from "lucide-react";

const iconMap = {
    sun: Sun,
    moon: Moon,
    user: User,
    arrowLeft: ArrowLeft,
    arrowDown: ArrowDown,
    mail: Mail,
    lock: Lock,
    chefHat: ChefHat,
    utensils: UtensilsCrossed,
    menu: Menu,
    x: X,
    chevronLeft: ChevronLeft,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    heart: Heart,
    coffee: Coffee,
    users: Users,
    mapPin: MapPin,
    clock: Clock,
    phone: Phone,
    send: Send,
    dashboard: LayoutDashboard,
    package: Package,
    warehouse: Warehouse,
    cart: ShoppingCart,
    trendingUp: TrendingUp,
    shoppingBag: ShoppingBag,
    fileText: FileText,
    settings: Settings,
    logOut: LogOut,
    bell: Bell,
    search: Search,
    alertTriangle: AlertTriangle,
    trendingDown: TrendingDown,
    lightbulb: Lightbulb,
    minus: Minus,
    edit: Edit,
    filter: SlidersHorizontal,
    image: Image,
    eye: Eye,
    eyeOff: EyeOff,
    pencil: Pencil,
    trash2: Trash2,
    plus: Plus,
    check: Check,
    checkCircle: CheckCircle,
    receipt: Receipt,
    calendar: Calendar,
    archive: Archive,
    circleArrowRight: CircleArrowRight,
    key: Key,
    dollarSign: DollarSign,
    cloudOff: CloudOff,
    barChart2: BarChart2,
    info: Info,
    alertCircle: AlertCircle,
    table: Table,
    sparkles: Sparkles,
    loader: Loader,
    camera: Camera,
    percent: Percent,
    layoutGrid: LayoutGrid,
    folderPlus: FolderPlus,
};

/**
 * Icon component
 * Wraps lucide-react icons for consistent usage across the app.
 * @param {string} name - icon name from iconMap
 * @param {number} size - icon size in px (default 20)
 * @param {string} className - tailwind classes
 */
export default function Icon({ name, size = 20, className = "" }) {
    const LucideIcon = iconMap[name];
    if (!LucideIcon) return null;

    return <LucideIcon size={size} className={className} />;
}